### ISSUE TITLE
Create release

### ISSUE THREAD

**Issue by ro0NL** [php-http/logger-plugin#24]
Can a release be made? I noticed #22 is not released yet -.-

https://github.com/php-http/logger-plugin/compare/1.3.0...master

Would be nice if `"request" => Nyholm\Psr7\Request^ { …},` disappeared from our prod logs.

cc @dbu

**Comment by dbu** [comment]
uh. it seems i tagged on my machine without having pulled after the merge of 22, and thats also why the changelog for 1.3.0 had no date yet... fixed this now, https://github.com/php-http/logger-plugin/releases/tag/1.3.1 includes #22.
