### ISSUE TITLE
Allow customizing the log context

### ISSUE THREAD

**Issue by ro0NL** [php-http/logger-plugin#28]
**Description**
Currently the log context is hardcoded:

https://github.com/php-http/logger-plugin/blob/4a2b447a5ba1a95c3869512ee992f5ba7fd9aa5f/src/LoggerPlugin.php#L34

https://github.com/php-http/logger-plugin/blob/4a2b447a5ba1a95c3869512ee992f5ba7fd9aa5f/src/LoggerPlugin.php#L39-L45

Ideally this packages provides an extended `LogFormatterInterface`, allowing for eg. request/response headers as log context.

Using the context fields usually provides better filtering by keyword in various systems (eg. graylog), compared to currently where we need to rely on regex filtering: `/.*keyword.*/`, which is counter intuitive.

This way we can share a common trace ID between various subsystems.

**Comment by ro0NL** [comment]
cc @dbu 

WDYT?

```php
interface LogFormatter {
   public function getLogContext(Request $request, ?Reponse $response): array;
}
```

This needs a new major first to cleanup/resolve current deprecations.

**Comment by ro0NL** [comment]
we're attemping a custom plugin instead, which should work pretty well using https://docs.php-http.org/en/latest/integrations/symfony-bundle.html#configure-a-custom-plugin

**Comment by dbu** [comment]
hi @ro0NL how did you solve this? if it is a small change, i am glad to accept a pull request. if its a lot of additional information, i think its better to write your own plugin - given how small this whole plugin is, it should not be too problematic to have your own logger plugin.

**Comment by ro0NL** [comment]
we solved it with a custom logger plugin + formatter, we prefer the flexibility :)

**Comment by dbu** [comment]
i think that is the right approach here, given how small the plugin is. thanks for the update.
