### ISSUE TITLE
Ability to affect the logger context

### ISSUE THREAD

**Issue by pascalwoerde** [php-http/logger-plugin#6]
| Q            | A
| ------------ | ---
| Bug?         | no
| New Feature? | yes

The PSR logger interface specifies a context to provide extra information for the message. Since the current implementation is bounded to a predefined context it is not possible to affect this. We could use a message factory or something to generate messages in a custom way as solution.

**Comment by dbu** [comment]
do you have some example use cases for when a specific context would be useful? and do you mean that the application should be able to add context, or that this factory would add more context?

**Comment by pascalwoerde** [comment]
For example, custom details like: hostname, client name, server name, api version, uuid, ... such details are useful for a more advanced logging. Yes the application should be able to add context, but we could also solve this with a factory. Which approach do you prefer?

**Comment by dbu** [comment]
don't we log the whole request and response with all headers in the context?

**Comment by pascalwoerde** [comment]
Do you suggest that any relevant details should be passed by the Request or Response in manner to receive such information?

The whole request and response with all the headers will be passed in the context, but sometimes optional logging information could be useful and is definitely not required as certain header or any other information in the request. A simple fix for now is to proxy the logger and inject any information later, but this does'nt feel as the right solution.

**Comment by dbu** [comment]
sorry, i was confused then. host name, client and server names, api version are often part of the request and response. but if you mean application (non-http) information, then of course that should not go into the http requests.

do you need to log those information only with logs of the logger plugin, or elsewhere? if you want to log them with each log entry, maybe using a [monolog processor](https://github.com/Seldaek/monolog/blob/master/doc/02-handlers-formatters-processors.md#processors) would be the best solution?

**Comment by pascalwoerde** [comment]
Sorry for the late response, I think you're right. Application information non related to the Request or Response can be supposed outside the logger e.g. for monolog with a processor. I can't find any situation at this moment that will not fit with such solution.

**Comment by dbu** [comment]
no worries, glad you found a good solution. the fewer things we add to the plugins, the easier they will be to understand, use and maintain ;-) but don't hesitate to ask again if you need something. and when changing the code of the plugins is the best solution, we also will do that.
